import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { createRequire } from 'node:module'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const desktopRoot = process.env.HERMES_DESKTOP_ROOT
if (!desktopRoot) throw new Error('Set HERMES_DESKTOP_ROOT to an existing Hermes desktop checkout with installed dependencies')
const requireHost = createRequire(path.join(path.resolve(desktopRoot), 'package.json'))
const load = name => import(pathToFileURL(requireHost.resolve(name)).href)
const { createServer } = await load('vite')
const { chromium } = requireHost('playwright')
const { default: tailwindcss } = await load('@tailwindcss/vite')
const names = ['react', 'react/jsx-runtime', 'react/jsx-dev-runtime', 'react-dom/client', '@tanstack/react-query', 'nanostores', '@nanostores/react']
const aliases = names.map(name => ({ find: new RegExp(`^${name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`), replacement: requireHost.resolve(name) }))
aliases.unshift({ find: '@hermes/plugin-sdk', replacement: path.join(root, 'scripts/qa/sdk.mjs') })
aliases.push({ find: /^tailwindcss$/, replacement: path.join(path.dirname(requireHost.resolve('tailwindcss/package.json')), 'index.css') })
const evidence = path.resolve(root, '.qa')
await fs.mkdir(evidence, { recursive: true })
const server = await createServer({ root, configFile: false, cacheDir: path.join(evidence, 'vite'), plugins: [tailwindcss()], resolve: { alias: aliases, dedupe: ['react', 'react-dom'] }, server: { host: '127.0.0.1', port: 0, fs: { allow: [root, path.resolve(desktopRoot), path.resolve(desktopRoot, '../..')] } } })
let browser
const checks = []
try {
  await server.listen()
  browser = await chromium.launch({ headless: true, ...(process.env.BLINKENBAR_BROWSER ? { executablePath: process.env.BLINKENBAR_BROWSER } : {}) })
  const context = await browser.newContext({ viewport: { width: 420, height: 580 }, deviceScaleFactor: process.argv.includes('--media') ? 1 : 2 })
  const page = await context.newPage()
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto(`${server.resolvedUrls.local[0]}scripts/qa/index.html`)
  await page.waitForFunction(() => window.qa?.polls > 0 && document.querySelector('canvas')?.width > 10)
  await page.waitForTimeout(350)
  if (process.argv.includes('--media')) {
    if (!process.env.BLINKENBAR_METRICS_FILE) throw new Error('Media capture requires an actual aggregate metrics JSON sample via BLINKENBAR_METRICS_FILE')
    const sample = JSON.parse(await fs.readFile(process.env.BLINKENBAR_METRICS_FILE, 'utf8'))
    assert.equal(sample.ok, true)
    await page.evaluate(data => { qa.metrics = data; qa.queryClient.invalidateQueries() }, sample)
    await page.waitForTimeout(300)
    const media = path.join(root, 'docs/media')
    await fs.mkdir(media, { recursive: true })
    for (const mode of ['EMBER', 'ION', 'VIOLET', 'MATRIX', 'THEME']) {
      assert.equal(await page.getByTitle('Cycle color mode').innerText(), mode)
      await page.locator('#pane').screenshot({ path: path.join(media, mode === 'EMBER' ? 'blinkenbar-hero.png' : `blinkenbar-mode-${mode.toLowerCase()}.png`) })
      await page.getByTitle('Cycle color mode').click()
      await page.waitForTimeout(150)
    }
    for (let index = 0; index < 3; index++) await page.getByTitle('Cycle idle fill pattern').click()
    await page.waitForTimeout(150)
    await page.locator('#pane').screenshot({ path: path.join(media, 'blinkenbar-quiet.png') })
    await page.getByTitle('Cycle idle fill pattern').click()
    const bannerContext = await browser.newContext({ viewport: { width: 600, height: 324 }, deviceScaleFactor: 2 })
    const bannerPage = await bannerContext.newPage()
    bannerPage.on('pageerror', error => errors.push(error.message))
    await bannerPage.goto(`${server.resolvedUrls.local[0]}scripts/qa/index.html`)
    await bannerPage.waitForFunction(() => window.qa?.polls > 0)
    await bannerPage.evaluate(data => { qa.metrics = data; qa.queryClient.invalidateQueries() }, sample)
    await bannerPage.waitForTimeout(300)
    await bannerPage.locator('#pane').screenshot({ path: path.join(media, 'blinkenbar-catalog.png') })
    await bannerContext.close()
    await page.setViewportSize({ width: 360, height: 504 })
    await page.waitForTimeout(250)
    const frames = path.join(evidence, 'frames')
    await fs.mkdir(frames, { recursive: true })
    for (let index = 0; index < 64; index++) {
      await page.locator('#pane').screenshot({ path: path.join(frames, `frame_${String(index).padStart(3, '0')}.png`) })
      await page.waitForTimeout(125)
    }
    assert.match(await page.locator('#chip').innerText(), /BLINK 0/)
    assert.deepEqual(errors, [])
    const result = { browser: browser.version(), viewport: '420x580; catalog 600x324 at DPR2; animation 360x504', dpr: 1, data: 'Actual local aggregate counter sample; idle agent, zero injected events; isolated SDK transport; dark test theme', images: 7, frames: 64, errors }
    await fs.writeFile(path.join(evidence, 'media-results.json'), JSON.stringify(result, null, 2))
    console.log(JSON.stringify(result, null, 2))
  } else {
  assert.equal(await page.locator('canvas').count(), 1)
  assert.equal(await page.locator('#chip button').count(), 0, 'Status chip must not inject demo events')
  assert.equal(await page.evaluate(() => qa.contributions.some(item => item.id === 'blinkenbar-test')), false)
  assert.equal(await page.locator('canvas').evaluate(el => getComputedStyle(el).cursor), 'auto')
  checks.push('passive canvas and chip; no signal-test command')
  const pixels = () => page.locator('canvas').evaluate(el => Array.from(el.getContext('2d').getImageData(0, 0, el.width, el.height).data))
  let before = await pixels()
  await page.waitForTimeout(400)
  let after = await pixels()
  assert(before.some((value, index) => value !== after[index]), 'Idle animation must remain alive')
  checks.push('idle animation changes actual canvas pixels')
  await page.evaluate(() => {
    qa.emit({ type: 'message.start', session_id: 'qa-session-a', profile: 'default', payload: {} })
    qa.emit({ type: 'subagent.start', session_id: 'qa-session-a', profile: 'default', payload: { subagent_id: 'fixture-child', depth: 1 } })
    qa.emit({ type: 'subagent.tool', session_id: 'qa-session-a', profile: 'default', payload: { subagent_id: 'fixture-child', tool_name: 'terminal' } })
  })
  await page.waitForTimeout(250)
  assert.match(await page.locator('#chip').innerText(), /BLINK 2/)
  checks.push('real plugin receives controlled host events and reports activity')
  for (const width of [220, 292, 420, 700]) {
    await page.setViewportSize({ width, height: 580 })
    await page.waitForTimeout(250)
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Overflow at ${width}`)
    const size = await page.locator('canvas').evaluate(el => ({ width: el.width, css: el.getBoundingClientRect().width }))
    assert(size.width >= size.css && size.css <= width)
    await page.screenshot({ path: path.join(evidence, `panel-${width}.png`) })
  }
  checks.push('220/292/420/700px widths at DPR 2; no document overflow')
  await page.setViewportSize({ width: 420, height: 580 })
  const modes = ['EMBER', 'ION', 'VIOLET', 'MATRIX', 'THEME']
  for (const mode of modes) {
    assert.equal(await page.getByTitle('Cycle color mode').innerText(), mode)
    await page.screenshot({ path: path.join(evidence, `mode-${mode.toLowerCase()}.png`) })
    await page.getByTitle('Cycle color mode').click()
    await page.waitForTimeout(140)
  }
  const pattern = page.getByTitle('Cycle idle fill pattern')
  for (let index = 0; index < 4; index++) { await pattern.click(); await page.waitForTimeout(140) }
  checks.push('all color and ambient controls exercised through DOM')
  await page.evaluate(() => { document.querySelector('#pane').style.transform = 'translateX(-2000px)' })
  await page.waitForTimeout(300)
  let polls = await page.evaluate(() => qa.polls)
  before = await pixels()
  await page.waitForTimeout(2300)
  assert.equal(await page.evaluate(() => qa.polls), polls, 'Hidden pane must stop polling')
  after = await pixels()
  assert.deepEqual(after, before, 'Hidden pane must stop painting')
  await page.evaluate(() => { document.querySelector('#pane').style.transform = '' })
  await page.waitForFunction(count => qa.polls > count, polls)
  checks.push('offscreen pane stops polling and pixels, resumes on return')
  await page.evaluate(() => { qa.fail = true; qa.queryClient.invalidateQueries() })
  await page.getByText(/TELEMETRY OFFLINE/).waitFor()
  await page.screenshot({ path: path.join(evidence, 'offline.png') })
  await page.evaluate(() => { qa.fail = false })
  await page.getByRole('button', { name: /retry/i }).click()
  await page.getByText(/PASSIVE TELEMETRY/).waitFor()
  assert.equal(await page.evaluate(() => qa.events.length), 0, 'Recovery should not announce gateway restart')
  checks.push('offline retry restores metrics without restarting host')
  await page.evaluate(() => {
    qa.emit({ type: 'subagent.complete', session_id: 'qa-session-a', profile: 'default', payload: { subagent_id: 'fixture-child' } })
    qa.emit({ type: 'subagent.progress', session_id: 'qa-session-a', profile: 'default', payload: { subagent_id: 'fixture-child', preview: 'must not retain' } })
  })
  await page.waitForTimeout(100)
  assert.match(await page.locator('#chip').innerText(), /BLINK 1/)
  checks.push('late progress does not resurrect completed child')
  await page.evaluate(() => {
    qa.emit({ type: 'message.start', connectionId: 'foreign', session_id: 'foreign-session', profile: 'default', payload: {} })
    qa.emit({ type: 'sessions.changed', profile: 'bot', payload: {} })
  })
  await page.waitForTimeout(100)
  assert.match(await page.locator('#chip').innerText(), /BLINK 1/)
  checks.push('foreign-connection and housekeeping events do not add live agents')
  await page.evaluate(() => qa.host.state.gateway.set('closed'))
  await page.waitForFunction(() => document.querySelector('#chip').innerText.includes('BLINK 0'))
  polls = await page.evaluate(() => qa.polls)
  await page.waitForTimeout(2200)
  assert.equal(await page.evaluate(() => qa.polls), polls)
  await page.screenshot({ path: path.join(evidence, 'disconnected.png') })
  await page.evaluate(() => qa.host.state.gateway.set('open'))
  await page.waitForFunction(count => qa.polls > count, polls)
  assert.match(await page.locator('#chip').innerText(), /BLINK 0/)
  await page.evaluate(() => qa.emit({ type: 'message.delta', connectionId: 'local', session_id: 'qa-session-a', profile: 'default', payload: {} }))
  await page.waitForFunction(() => document.querySelector('#chip').innerText.includes('BLINK 1'))
  checks.push('disconnect stops activity claims and polling; only fresh events resume activity')
  await page.evaluate(() => qa.unmount())
  assert.equal(await page.evaluate(() => qa.listenerCount()), 0)
  polls = await page.evaluate(() => qa.polls)
  await page.waitForTimeout(2200)
  assert.equal(await page.evaluate(() => qa.polls), polls)
  assert.deepEqual(errors, [])
  checks.push('unmount disposes host listener and polling; no browser exceptions')
  const result = { browser: browser.version(), renderer: 'Chromium Canvas2D, real plugin + React/Query, test-only SDK boundary', checks, errors }
  await fs.writeFile(path.join(evidence, 'results.json'), JSON.stringify(result, null, 2))
  console.log(JSON.stringify(result, null, 2))
  }
} finally {
  await browser?.close()
  await server.close()
}
